"""
CZ Dashboard API — FastAPI backend.

Reads the snapshot generated by `scripts/export_control_panel.py` and exposes
filtered views + KPIs + AI chat. See SPEC.md for full contract.

Run locally:
    cd apps/api
    pip install -r requirements.txt
    cp .env.example .env  # fill keys
    uvicorn main:app --reload --port 8000
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import threading
import time
from collections.abc import Iterable
from pathlib import Path
from typing import Any, Literal

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, StreamingResponse
from pydantic import BaseModel, Field

# ─── Paths & env ──────────────────────────────────────────────────────────────

REPO_ROOT = Path(__file__).resolve().parents[2]
load_dotenv(REPO_ROOT / "apps" / "api" / ".env")
load_dotenv(REPO_ROOT / ".env", override=False)

SNAPSHOT_PATH = REPO_ROOT / os.getenv("SNAPSHOT_PATH", "reports/trades_snapshot_latest.json")
SNAPSHOT_CACHE_TTL = int(os.getenv("SNAPSHOT_CACHE_TTL", "300"))
CORS_ORIGINS = [o.strip() for o in os.getenv("CORS_ORIGINS", "http://localhost:3000").split(",") if o.strip()]
GDRIVE_ID = "1RIXpDUIq1692_6UwoPFYyrKtukYB2UArCTWvI6Y5Xbk"
MONTH_SHEET_REGEX = re.compile(r"^(JS )?[A-Z]{3}\d{2}$")
MONTH_NUM = {
    "JAN": 1,
    "FEB": 2,
    "MAR": 3,
    "APR": 4,
    "MAY": 5,
    "JUN": 6,
    "JUL": 7,
    "AUG": 8,
    "SEP": 9,
    "OCT": 10,
    "NOV": 11,
    "DEC": 12,
}

# ─── App ──────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="CZ Dashboard API",
    version="0.1.0",
    description="Backend for the CZ trading dashboard. See SPEC.md.",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["GET", "POST", "OPTIONS"],
    allow_headers=["*"],
    expose_headers=["X-Snapshot-Generated-At"],
)

# ─── Snapshot cache ───────────────────────────────────────────────────────────

_snapshot_cache: dict[str, Any] = {"data": None, "loaded_at": 0.0, "mtime": 0.0}
_refresh_lock = threading.Lock()
_refresh_running = {"state": False}


def load_snapshot(force: bool = False) -> dict[str, Any]:
    if not SNAPSHOT_PATH.exists():
        raise HTTPException(503, f"Snapshot not found at {SNAPSHOT_PATH}. Run scripts/export_control_panel.py first.")
    mtime = SNAPSHOT_PATH.stat().st_mtime
    age = time.time() - _snapshot_cache["loaded_at"]
    fresh_enough = (
        not force
        and _snapshot_cache["data"] is not None
        and age < SNAPSHOT_CACHE_TTL
        and mtime == _snapshot_cache["mtime"]
    )
    if not fresh_enough:
        with SNAPSHOT_PATH.open(encoding="utf-8") as f:
            _snapshot_cache["data"] = json.load(f)
        _snapshot_cache["loaded_at"] = time.time()
        _snapshot_cache["mtime"] = mtime
    return _snapshot_cache["data"]


# ─── Filter helpers ───────────────────────────────────────────────────────────

# Map sheet names → environment (matches scripts/export_control_panel.py SHEET_ENV_MAP)
SHEET_TO_ENV: dict[str, str] = {
    "APR26": "CZ_Live",
    "MAR26": "CZ_Live",
    "JS APR26": "JS_Forward",
    "JS-FOR MAR26": "JS_Forward",
    "FOR Trades": "CZ_Forward",
}


def parse_months(months: str | None) -> list[str]:
    if not months:
        return []
    return [m.strip() for m in months.split(",") if m.strip()]


def trade_in_filter(trade: dict[str, Any], months: list[str], env: str | None) -> bool:
    sheet = (trade.get("sheet") or "").strip()
    valid_sheet = bool(sheet and MONTH_SHEET_REGEX.match(sheet))
    if months and (not valid_sheet or sheet not in months):
        return False
    if env and trade.get("environment") != env:
        return False
    return True


def trade_pnl(trade: dict[str, Any], individual: dict[str, float]) -> float:
    """Best-effort PnL extraction across snapshot field name variants."""
    if trade.get("name") in individual:
        return float(individual[trade["name"]])
    for key in ("pnl_current", "open_pnl", "pnl"):
        v = trade.get(key)
        if v is not None:
            return float(v)
    return 0.0


def trade_delta(trade: dict[str, Any]) -> float:
    for key in ("delta_current", "delta"):
        v = trade.get(key)
        if v is not None:
            return float(v)
    return 0.0


# ─── Pydantic models ──────────────────────────────────────────────────────────


class HealthResponse(BaseModel):
    status: Literal["ok"] = "ok"
    snapshot_age_seconds: float | None
    snapshot_generated_at: str | None


class MonthInfo(BaseModel):
    sheet: str
    env: str
    label: str
    n_trades: int
    active: bool


class MonthsResponse(BaseModel):
    months: list[MonthInfo]


class FilterEcho(BaseModel):
    months: list[str]
    env: str | None


class TradesResponse(BaseModel):
    filter: FilterEcho
    trades: list[dict[str, Any]]


class KpisResponse(BaseModel):
    filter: FilterEcho
    pnl: dict[str, float]
    risk: dict[str, float]
    performance: dict[str, float | None]
    trade_intel: dict[str, Any]


class ChatMessage(BaseModel):
    role: Literal["user", "assistant", "system"]
    content: str


class ChatRequest(BaseModel):
    messages: list[ChatMessage]
    filter: FilterEcho = Field(default_factory=lambda: FilterEcho(months=[], env=None))
    provider: Literal["anthropic", "openai"] = "anthropic"


# ─── Endpoints ────────────────────────────────────────────────────────────────


@app.get("/api/health", response_model=HealthResponse)
def health() -> HealthResponse:
    if not SNAPSHOT_PATH.exists():
        return HealthResponse(snapshot_age_seconds=None, snapshot_generated_at=None)
    snap = load_snapshot()
    return HealthResponse(
        snapshot_age_seconds=time.time() - SNAPSHOT_PATH.stat().st_mtime,
        snapshot_generated_at=snap.get("generated_at"),
    )


@app.get("/api/snapshot")
def get_snapshot() -> JSONResponse:
    snap = load_snapshot()
    return JSONResponse(
        snap,
        headers={
            "X-Snapshot-Generated-At": str(snap.get("generated_at", "")),
            "Cache-Control": f"max-age={SNAPSHOT_CACHE_TTL}",
        },
    )


@app.post("/api/snapshot/refresh")
def refresh_snapshot() -> JSONResponse:
    with _refresh_lock:
        if _refresh_running["state"]:
            return JSONResponse({"status": "already_running"}, status_code=409)
        _refresh_running["state"] = True

    def run() -> None:
        try:
            print("[snapshot refresh] running export_control_panel.py")
            proc = subprocess.run(
                [
                    sys.executable,
                    str(REPO_ROOT / "scripts" / "export_control_panel.py"),
                    "--gdrive-id",
                    GDRIVE_ID,
                ],
                cwd=str(REPO_ROOT),
                check=False,
                capture_output=True,
                text=True,
                timeout=300,
            )
            if proc.stdout:
                print(proc.stdout, end="")
            if proc.stderr:
                print(proc.stderr, end="", file=sys.stderr)
            print(f"[snapshot refresh] finished rc={proc.returncode}")
        except subprocess.TimeoutExpired:
            print("[snapshot refresh] exporter timed out after 300s", file=sys.stderr)
        finally:
            _snapshot_cache["data"] = None
            with _refresh_lock:
                _refresh_running["state"] = False

    threading.Thread(target=run, daemon=True).start()
    return JSONResponse({"status": "refresh_started"}, status_code=202)


@app.get("/api/months", response_model=MonthsResponse)
def get_months() -> MonthsResponse:
    snap = load_snapshot()
    sheet_months: dict[str, dict[str, Any]] = {}
    for trade in snap.get("trades", []):
        sheet = (trade.get("sheet") or "").strip()
        if not sheet or not MONTH_SHEET_REGEX.match(sheet):
            continue
        env = trade.get("environment") or SHEET_TO_ENV.get(sheet, "Unknown")
        info = sheet_months.setdefault(sheet, {"sheet": sheet, "env": env, "n_trades": 0, "active": False})
        info["n_trades"] += 1
        if trade.get("is_active"):
            info["active"] = True

    months = [
        MonthInfo(
            sheet=info["sheet"],
            env=info["env"],
            label=_pretty_month_label(info["sheet"]),
            n_trades=info["n_trades"],
            active=info["active"],
        )
        for info in sheet_months.values()
    ]

    def sort_key(month: MonthInfo) -> tuple[int, int, int, str]:
        code = month.sheet.split()[-1]
        mon = code[:3]
        year = int(code[3:]) if len(code) == 5 and code[3:].isdigit() else -1
        month_num = MONTH_NUM.get(mon, -1)
        return (-int(month.active), -year, -month_num, month.sheet)

    months.sort(key=sort_key)
    return MonthsResponse(months=months)


@app.get("/api/trades", response_model=TradesResponse)
def get_trades(
    month: str | None = Query(None, description="Comma-separated month codes (e.g. APR26,MAR26)"),
    env: str | None = Query(None, description="Environment filter (CZ_Live, JS_Forward, CZ_Forward)"),
) -> TradesResponse:
    snap = load_snapshot()
    months = parse_months(month)
    trades = [t for t in snap.get("trades", []) if trade_in_filter(t, months, env)]

    # Normalize PnL into the unified `pnl` field that the frontend reads.
    individual_pnls = snap.get("individual_trade_pnls") or {}
    for t in trades:
        t["pnl"] = trade_pnl(t, individual_pnls)
        t["delta"] = trade_delta(t)

    return TradesResponse(filter=FilterEcho(months=months, env=env), trades=trades)


@app.get("/api/kpis", response_model=KpisResponse)
def get_kpis(
    month: str | None = Query(None),
    env: str | None = Query(None),
) -> KpisResponse:
    snap = load_snapshot()
    months = parse_months(month)
    trades = [t for t in snap.get("trades", []) if trade_in_filter(t, months, env)]
    individual_pnls = snap.get("individual_trade_pnls") or {}

    open_pnl = 0.0
    rlzd = 0.0
    delta_total = 0.0
    max_loss_exposed = 0.0
    net_credit_at_risk = 0.0
    n_active = 0
    n_closed = 0
    closed_pnls: list[float] = []
    daily_theta = 0.0

    for t in trades:
        pnl = trade_pnl(t, individual_pnls)
        is_active = bool(t.get("is_active"))
        if is_active:
            n_active += 1
            open_pnl += pnl
            delta_total += trade_delta(t)
            max_loss_exposed += float(t.get("max_loss") or 0)
            net_credit_at_risk += float(t.get("net_credit") or 0)
            dte = t.get("dte_remaining")
            nc = t.get("net_credit")
            if dte and nc and dte > 0:
                daily_theta += float(nc) / float(dte)
        else:
            n_closed += 1
            rlzd += pnl
            closed_pnls.append(pnl)

    wins = [p for p in closed_pnls if p > 0]
    losses = [p for p in closed_pnls if p < 0]
    win_rate = len(wins) / len(closed_pnls) if closed_pnls else None
    profit_factor = (sum(wins) / abs(sum(losses))) if losses and sum(losses) else None
    expectancy = (sum(closed_pnls) / len(closed_pnls)) if closed_pnls else None

    return KpisResponse(
        filter=FilterEcho(months=months, env=env),
        pnl={
            "open": round(open_pnl, 2),
            "rlzd": round(rlzd, 2),
            "delta": round(delta_total, 2),
            "max_profit": round(net_credit_at_risk, 2),
        },
        risk={
            "max_loss_exposed": round(max_loss_exposed, 2),
            "net_credit_at_risk": round(net_credit_at_risk, 2),
            "est_daily_theta": round(daily_theta, 2),
        },
        performance={
            "win_rate": round(win_rate, 4) if win_rate is not None else None,
            "profit_factor": round(profit_factor, 2) if profit_factor is not None else None,
            "expectancy": round(expectancy, 2) if expectancy is not None else None,
        },
        trade_intel={
            "best_trade": round(max(closed_pnls), 2) if closed_pnls else None,
            "worst_trade": round(min(closed_pnls), 2) if closed_pnls else None,
            "n_active": n_active,
            "n_closed": n_closed,
        },
    )


@app.post("/api/chat")
async def chat(req: ChatRequest, request: Request) -> StreamingResponse:
    snap = load_snapshot()
    months = req.filter.months
    env = req.filter.env
    trades = [t for t in snap.get("trades", []) if trade_in_filter(t, months, env)]

    system_prompt = _build_system_prompt(trades, snap, months, env)
    messages = [{"role": m.role, "content": m.content} for m in req.messages if m.role != "system"]

    if req.provider == "anthropic":
        return StreamingResponse(_stream_anthropic(system_prompt, messages), media_type="text/event-stream")
    return StreamingResponse(_stream_openai(system_prompt, messages), media_type="text/event-stream")


# ─── Internals ────────────────────────────────────────────────────────────────


def _pretty_month_label(sheet: str) -> str:
    # APR26 → "Apr 2026"; "JS APR26" → "JS Apr 2026"; "FOR Trades" → "FOR Trades"
    months_map = {
        "JAN": "Jan", "FEB": "Feb", "MAR": "Mar", "APR": "Apr", "MAY": "May", "JUN": "Jun",
        "JUL": "Jul", "AUG": "Aug", "SEP": "Sep", "OCT": "Oct", "NOV": "Nov", "DEC": "Dec",
    }
    parts = sheet.split()
    out: list[str] = []
    for p in parts:
        if len(p) == 5 and p[:3] in months_map and p[3:].isdigit():
            out.append(f"{months_map[p[:3]]} 20{p[3:]}")
        else:
            out.append(p)
    return " ".join(out)


def _build_system_prompt(trades: list[dict[str, Any]], snap: dict[str, Any], months: list[str], env: str | None) -> str:
    filter_desc = f"months={months or 'ALL'}, env={env or 'ALL'}"
    individual = snap.get("individual_trade_pnls") or {}
    trade_lines: list[str] = []
    for t in trades:
        name = t.get("name", "?")
        pnl = trade_pnl(t, individual)
        trade_lines.append(
            f"- {name} ({t.get('underlying','?')}, {t.get('environment_raw','?')}): "
            f"PnL=${pnl:.0f}, status={'ACTIVE' if t.get('is_active') else 'CLOSED'}, "
            f"Δ={trade_delta(t):.1f}, DTE={t.get('dte_remaining','—')}, "
            f"NC=${t.get('net_credit','—')}, MaxLoss=${t.get('max_loss','—')}"
        )
    trade_block = "\n".join(trade_lines) if trade_lines else "(no trades match the current filter)"

    return (
        "You are the CZ Dashboard AI — an analytical assistant embedded in Cristiano's "
        "proprietary trading desk dashboard. You analyze the trades shown below to help "
        "identify leaks, correlations, strengths, weaknesses, and structural patterns.\n\n"
        f"Active filter: {filter_desc}\n"
        f"Snapshot generated at: {snap.get('generated_at','?')}\n\n"
        f"Trades in scope:\n{trade_block}\n\n"
        "Hard rules:\n"
        "- NEVER recommend specific trade execution (entry/exit). Cristiano executes; you analyze.\n"
        "- Be concise, quantitative, and direct. No fluff.\n"
        "- When discussing PnL, always cite the specific trade names from above.\n"
        "- If asked about data not in the trade list, say so explicitly.\n"
    )


async def _stream_anthropic(system: str, messages: list[dict[str, str]]) -> Iterable[bytes]:
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        yield _sse({"error": "ANTHROPIC_API_KEY not set", "done": True})
        return
    try:
        from anthropic import AsyncAnthropic
    except ImportError:
        yield _sse({"error": "anthropic SDK not installed", "done": True})
        return

    client = AsyncAnthropic(api_key=api_key)
    async with client.messages.stream(
        model="claude-sonnet-4-6",
        max_tokens=2048,
        system=system,
        messages=messages,
    ) as stream:
        async for text in stream.text_stream:
            yield _sse({"delta": text, "done": False})
    yield _sse({"done": True})


async def _stream_openai(system: str, messages: list[dict[str, str]]) -> Iterable[bytes]:
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        yield _sse({"error": "OPENAI_API_KEY not set", "done": True})
        return
    try:
        from openai import AsyncOpenAI
    except ImportError:
        yield _sse({"error": "openai SDK not installed", "done": True})
        return

    client = AsyncOpenAI(api_key=api_key)
    full_messages = [{"role": "system", "content": system}, *messages]
    stream = await client.chat.completions.create(
        model="gpt-4o-mini",
        messages=full_messages,
        stream=True,
    )
    async for chunk in stream:
        delta = chunk.choices[0].delta.content if chunk.choices and chunk.choices[0].delta else None
        if delta:
            yield _sse({"delta": delta, "done": False})
    yield _sse({"done": True})


def _sse(payload: dict[str, Any]) -> bytes:
    return f"data: {json.dumps(payload, ensure_ascii=False)}\n\n".encode("utf-8")
