"""
ST | Dashboard API — FastAPI backend.

Reads the snapshot generated by `scripts/export_control_panel.py` and exposes
filtered views + KPIs + AI chat. See SPEC.md for full contract.

Run locally:
    cd apps/api
    pip install -r requirements.txt
    cp .env.example .env  # fill keys
    uvicorn main:app --reload --port 8000
"""

from __future__ import annotations

import json
import csv
import os
import re
import subprocess
import sys
import threading
import time
from collections.abc import AsyncIterator, Iterable
from contextlib import asynccontextmanager
from datetime import datetime
from pathlib import Path
from typing import Any, Literal

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, Response, StreamingResponse
from pydantic import BaseModel, Field

# ─── Paths & env ──────────────────────────────────────────────────────────────

REPO_ROOT = Path(__file__).resolve().parents[2]
load_dotenv(REPO_ROOT / "apps" / "api" / ".env")
load_dotenv(REPO_ROOT / ".env", override=False)

SNAPSHOT_PATH = REPO_ROOT / os.getenv("SNAPSHOT_PATH", "reports/trades_snapshot_latest.json")
SNAPSHOT_CACHE_TTL = int(os.getenv("SNAPSHOT_CACHE_TTL", "300"))
CORS_ORIGINS = [o.strip() for o in os.getenv("CORS_ORIGINS", "http://localhost:3000").split(",") if o.strip()]
GDRIVE_ID = os.getenv("GDRIVE_FILE_ID", "1RIXpDUIq1692_6UwoPFYyrKtukYB2UArCTWvI6Y5Xbk")
MONTH_SHEET_REGEX = re.compile(r"^(JS )?[A-Z]{3}\d{2}$")
MONTH_NUM = {
    "JAN": 1,
    "FEB": 2,
    "MAR": 3,
    "APR": 4,
    "MAY": 5,
    "JUN": 6,
    "JUL": 7,
    "AUG": 8,
    "SEP": 9,
    "OCT": 10,
    "NOV": 11,
    "DEC": 12,
}

# ─── App + scheduler lifecycle ────────────────────────────────────────────────


def _env_flag(name: str, default: str = "0") -> bool:
    return os.getenv(name, default).strip().lower() in ("1", "true", "yes", "on")


@asynccontextmanager
async def lifespan(_app: FastAPI) -> AsyncIterator[None]:
    """Boots the snapshot scheduler when SCHEDULER_ENABLED is truthy.

    Cron: every SCHEDULER_INTERVAL_MIN minutes, weekdays, between SCHEDULER_HOURS
    (default 9-16) in SCHEDULER_TZ (default America/New_York). Each tick triggers
    the same export pipeline as the manual refresh button — same lock, same cache
    invalidation, so doubles can't pile up.
    """
    scheduler = None
    if _env_flag("SCHEDULER_ENABLED"):
        try:
            from apscheduler.schedulers.background import BackgroundScheduler
            from apscheduler.triggers.cron import CronTrigger
        except ImportError:
            print("[scheduler] apscheduler not installed — skip", file=sys.stderr)
        else:
            tz = os.getenv("SCHEDULER_TZ", "America/New_York")
            interval = max(1, int(os.getenv("SCHEDULER_INTERVAL_MIN", "10")))
            hours = os.getenv("SCHEDULER_HOURS", "9-16")
            days = os.getenv("SCHEDULER_DAYS", "mon-fri")
            scheduler = BackgroundScheduler(timezone=tz)
            scheduler.add_job(
                lambda: _trigger_export_script(source="scheduler"),
                CronTrigger(
                    minute=f"*/{interval}",
                    hour=hours,
                    day_of_week=days,
                    timezone=tz,
                ),
                id="snapshot_refresh",
                max_instances=1,
                coalesce=True,
                misfire_grace_time=300,
            )
            scheduler.start()
            print(f"[scheduler] started — */{interval}min, hours={hours}, days={days}, tz={tz}")
    else:
        print("[scheduler] disabled (set SCHEDULER_ENABLED=1 to enable)")

    try:
        yield
    finally:
        if scheduler is not None:
            scheduler.shutdown(wait=False)
            print("[scheduler] stopped")


app = FastAPI(
    title="ST | Dashboard API",
    version="0.1.0",
    description="Backend for the ST trading dashboard. See SPEC.md.",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["GET", "POST", "OPTIONS"],
    allow_headers=["*"],
    expose_headers=["X-Snapshot-Generated-At"],
)

# ─── Snapshot cache ───────────────────────────────────────────────────────────

_snapshot_cache: dict[str, Any] = {"data": None, "loaded_at": 0.0, "mtime": 0.0}
_refresh_lock = threading.Lock()
_refresh_running = {"state": False}


def load_snapshot(force: bool = False) -> dict[str, Any]:
    if not SNAPSHOT_PATH.exists():
        raise HTTPException(503, f"Snapshot not found at {SNAPSHOT_PATH}. Run scripts/export_control_panel.py first.")
    mtime = SNAPSHOT_PATH.stat().st_mtime
    age = time.time() - _snapshot_cache["loaded_at"]
    fresh_enough = (
        not force
        and _snapshot_cache["data"] is not None
        and age < SNAPSHOT_CACHE_TTL
        and mtime == _snapshot_cache["mtime"]
    )
    if not fresh_enough:
        with SNAPSHOT_PATH.open(encoding="utf-8") as f:
            _snapshot_cache["data"] = json.load(f)
        _snapshot_cache["loaded_at"] = time.time()
        _snapshot_cache["mtime"] = mtime
    return _snapshot_cache["data"]


# ─── Filter helpers ───────────────────────────────────────────────────────────

# Map sheet names → environment (matches scripts/export_control_panel.py SHEET_ENV_MAP)
SHEET_TO_ENV: dict[str, str] = {
    "APR26": "CZ_Live",
    "MAR26": "CZ_Live",
    "JS APR26": "JS_Forward",
    "JS-FOR MAR26": "JS_Forward",
    "FOR Trades": "CZ_Forward",
}


def parse_months(months: str | None) -> list[str]:
    if not months:
        return []
    parsed = [m.strip() for m in months.split(",") if m.strip()]
    return sorted(parsed, key=_month_sort_tuple)


def trade_in_filter(trade: dict[str, Any], months: list[str], env: str | None) -> bool:
    sheet = (trade.get("sheet") or "").strip()
    valid_sheet = bool(sheet and MONTH_SHEET_REGEX.match(sheet))
    if months and (not valid_sheet or sheet not in months):
        return False
    if env and trade.get("environment") != env:
        return False
    return True


def trade_pnl(trade: dict[str, Any], individual: dict[str, float]) -> float:
    """Best-effort PnL extraction across snapshot field name variants."""
    if trade.get("name") in individual:
        return float(individual[trade["name"]])
    for key in ("pnl_current", "open_pnl", "pnl"):
        v = trade.get(key)
        if v is not None:
            return float(v)
    return 0.0


def trade_delta(trade: dict[str, Any]) -> float:
    for key in ("delta_current", "delta"):
        v = trade.get(key)
        if v is not None:
            return float(v)
    return 0.0


def sheet_summary_lookup(snap: dict[str, Any]) -> dict[str, dict[str, Any]]:
    summaries: dict[str, dict[str, Any]] = {}
    for env_name, env_summaries in (snap.get("sheet_summaries") or {}).items():
        for summary in env_summaries or []:
            sheet = summary.get("month")
            if isinstance(sheet, str):
                summaries[sheet] = {**summary, "env": env_name}
    return summaries


def strategy_family(name: str) -> str:
    n = name.upper()
    if "IRON CONDOR" in n or " IC" in n or "IC7" in n or "IC8" in n:
        return "Iron Condor"
    if "RJL" in n:
        return "RJL"
    if "BATMAN" in n or " BAT" in n or "BAT42" in n or "BAT7" in n:
        return "Batman / BWB"
    if "CALL BEAR" in n or "BEAR CALL" in n:
        return "Bear Call"
    if "BULL PUT" in n or "PUT CREDIT" in n or "PCS" in n:
        return "Bull Put"
    if "BULL CALL" in n:
        return "Bull Call"
    if "HALF-CALL" in n or "CALL-HALF" in n:
        return "Half Call"
    if "PUT-HALF" in n or "PUT BROKEN" in n:
        return "Put Broken Wing"
    return "Other"


def parse_iso_date(value: Any) -> datetime | None:
    if not value:
        return None
    try:
        return datetime.fromisoformat(str(value)[:10])
    except ValueError:
        return None


def trade_open_weekday(trade: dict[str, Any]) -> str:
    dt = parse_iso_date(trade.get("visual_open_date") or trade.get("open_date"))
    return dt.strftime("%a") if dt else "Unknown"


def trade_close_weekday(trade: dict[str, Any]) -> str:
    return str(trade.get("inferred_close_weekday") or "Unknown")


def trade_days_held(trade: dict[str, Any]) -> int | None:
    value = trade.get("days_held")
    if value is None:
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def trade_pnl_event_date(trade: dict[str, Any]) -> str:
    if not trade.get("is_active") and trade.get("inferred_close_date"):
        return str(trade["inferred_close_date"])[:10]
    for key in ("visual_last_pnl_date", "last_update", "visual_open_date", "open_date"):
        value = trade.get(key)
        if value:
            return str(value)[:10]
    return "Unknown"


def trade_dte_bucket(trade: dict[str, Any]) -> str:
    if trade.get("dte_bucket"):
        return str(trade["dte_bucket"])
    dte = trade.get("visual_dte_open") or trade.get("dte_open")
    if dte is None:
        return "Unknown"
    dte = int(dte)
    if dte <= 10:
        return "7 DTE"
    if dte <= 24:
        return "14/21 DTE"
    if dte <= 32:
        return "28 DTE"
    return "35/42 DTE"


# ─── Pydantic models ──────────────────────────────────────────────────────────


class HealthResponse(BaseModel):
    status: Literal["ok"] = "ok"
    snapshot_age_seconds: float | None
    snapshot_generated_at: str | None


class MonthInfo(BaseModel):
    sheet: str
    env: str
    label: str
    n_trades: int
    active: bool


class MonthsResponse(BaseModel):
    months: list[MonthInfo]


class FilterEcho(BaseModel):
    months: list[str]
    env: str | None


class TradesResponse(BaseModel):
    filter: FilterEcho
    trades: list[dict[str, Any]]


class KpisResponse(BaseModel):
    filter: FilterEcho
    pnl: dict[str, float]
    risk: dict[str, float]
    performance: dict[str, float | None]
    trade_intel: dict[str, Any]


class ChatMessage(BaseModel):
    role: Literal["user", "assistant", "system"]
    content: str


class ChatRequest(BaseModel):
    messages: list[ChatMessage]
    filter: FilterEcho = Field(default_factory=lambda: FilterEcho(months=[], env=None))
    provider: Literal["anthropic", "openai"] = "openai"


# ─── Endpoints ────────────────────────────────────────────────────────────────


@app.get("/api/health", response_model=HealthResponse)
def health() -> HealthResponse:
    if not SNAPSHOT_PATH.exists():
        return HealthResponse(snapshot_age_seconds=None, snapshot_generated_at=None)
    snap = load_snapshot()
    return HealthResponse(
        snapshot_age_seconds=time.time() - SNAPSHOT_PATH.stat().st_mtime,
        snapshot_generated_at=snap.get("generated_at"),
    )


@app.head("/api/health")
def health_head() -> Response:
    return Response(status_code=200)


@app.get("/api/snapshot")
def get_snapshot() -> JSONResponse:
    snap = load_snapshot()
    return JSONResponse(
        snap,
        headers={
            "X-Snapshot-Generated-At": str(snap.get("generated_at", "")),
            "Cache-Control": f"max-age={SNAPSHOT_CACHE_TTL}",
        },
    )


def _trigger_export_script(*, source: str = "manual") -> bool:
    """Spawns the export pipeline in a background thread.

    Returns True if a refresh was started, False if one was already running.
    Shared by the manual `/api/snapshot/refresh` endpoint and the cron scheduler.
    """
    with _refresh_lock:
        if _refresh_running["state"]:
            print(f"[snapshot refresh:{source}] skipped — already running")
            return False
        _refresh_running["state"] = True

    def run() -> None:
        try:
            print(f"[snapshot refresh:{source}] running export_control_panel.py")
            proc = subprocess.run(
                [
                    sys.executable,
                    str(REPO_ROOT / "scripts" / "export_control_panel.py"),
                    "--gdrive-id",
                    GDRIVE_ID,
                ],
                cwd=str(REPO_ROOT),
                check=False,
                capture_output=True,
                text=True,
                timeout=300,
            )
            if proc.stdout:
                print(proc.stdout, end="")
            if proc.stderr:
                print(proc.stderr, end="", file=sys.stderr)
            print(f"[snapshot refresh:{source}] finished rc={proc.returncode}")
        except subprocess.TimeoutExpired:
            print(f"[snapshot refresh:{source}] exporter timed out after 300s", file=sys.stderr)
        finally:
            _snapshot_cache["data"] = None
            with _refresh_lock:
                _refresh_running["state"] = False

    threading.Thread(target=run, daemon=True).start()
    return True


@app.post("/api/snapshot/refresh")
def refresh_snapshot() -> JSONResponse:
    if not _trigger_export_script(source="manual"):
        return JSONResponse({"status": "already_running"}, status_code=409)
    return JSONResponse({"status": "refresh_started"}, status_code=202)


@app.get("/api/months", response_model=MonthsResponse)
def get_months() -> MonthsResponse:
    snap = load_snapshot()
    sheet_months: dict[str, dict[str, Any]] = {}
    for trade in snap.get("trades", []):
        sheet = (trade.get("sheet") or "").strip()
        if not sheet or not MONTH_SHEET_REGEX.match(sheet):
            continue
        env = trade.get("environment") or SHEET_TO_ENV.get(sheet, "Unknown")
        info = sheet_months.setdefault(sheet, {"sheet": sheet, "env": env, "n_trades": 0, "active": False})
        info["n_trades"] += 1
        if trade.get("is_active"):
            info["active"] = True

    months = [
        MonthInfo(
            sheet=info["sheet"],
            env=info["env"],
            label=_pretty_month_label(info["sheet"]),
            n_trades=info["n_trades"],
            active=info["active"],
        )
        for info in sheet_months.values()
    ]

    months.sort(key=_month_filter_sort_tuple)
    return MonthsResponse(months=months)


@app.get("/api/trades", response_model=TradesResponse)
def get_trades(
    month: str | None = Query(None, description="Comma-separated month codes (e.g. APR26,MAR26)"),
    env: str | None = Query(None, description="Environment filter (CZ_Live, JS_Forward, CZ_Forward)"),
) -> TradesResponse:
    snap = load_snapshot()
    months = parse_months(month)
    trades = [t for t in snap.get("trades", []) if trade_in_filter(t, months, env)]

    # Normalize PnL/delta and backfill display fields for visual-only orphan trades
    # (source=visual_sheet) that don't have a current db_robots row.
    individual_pnls = snap.get("individual_trade_pnls") or {}
    today = datetime.utcnow().date()
    for t in trades:
        t["pnl"] = trade_pnl(t, individual_pnls)
        t["delta"] = trade_delta(t)
        if t.get("dte_open") is None and t.get("visual_dte_open") is not None:
            t["dte_open"] = t["visual_dte_open"]
        if t.get("open_date") is None and t.get("visual_open_date"):
            t["open_date"] = t["visual_open_date"]
        if t.get("exp_date") is None and t.get("visual_exp_date"):
            t["exp_date"] = t["visual_exp_date"]
        if t.get("dte_remaining") is None and t.get("exp_date"):
            exp = parse_iso_date(t["exp_date"])
            if exp:
                t["dte_remaining"] = (exp.date() - today).days

    return TradesResponse(filter=FilterEcho(months=months, env=env), trades=trades)


@app.get("/api/kpis", response_model=KpisResponse)
def get_kpis(
    month: str | None = Query(None),
    env: str | None = Query(None),
) -> KpisResponse:
    snap = load_snapshot()
    months = parse_months(month)
    trades = [t for t in snap.get("trades", []) if trade_in_filter(t, months, env)]
    individual_pnls = snap.get("individual_trade_pnls") or {}

    open_pnl = 0.0
    rlzd = 0.0
    delta_total = 0.0
    max_loss_exposed = 0.0
    net_credit_at_risk = 0.0
    n_active = 0
    n_closed = 0
    closed_pnls: list[float] = []
    daily_theta = 0.0

    for t in trades:
        pnl = trade_pnl(t, individual_pnls)
        is_active = bool(t.get("is_active"))
        if is_active:
            n_active += 1
            open_pnl += pnl
            delta_total += trade_delta(t)
            max_loss_exposed += float(t.get("max_loss") or 0)
            net_credit_at_risk += float(t.get("net_credit") or 0)
            dte = t.get("dte_remaining")
            nc = t.get("net_credit")
            if dte and nc and dte > 0:
                daily_theta += float(nc) / float(dte)
        else:
            n_closed += 1
            rlzd += pnl
            closed_pnls.append(pnl)

    wins = [p for p in closed_pnls if p > 0]
    losses = [p for p in closed_pnls if p < 0]
    win_rate = len(wins) / len(closed_pnls) if closed_pnls else None
    profit_factor = (sum(wins) / abs(sum(losses))) if losses and sum(losses) else None
    expectancy = (sum(closed_pnls) / len(closed_pnls)) if closed_pnls else None

    sheet_summaries = sheet_summary_lookup(snap)
    selected_summaries = [
        sheet_summaries[m]
        for m in months
        if m in sheet_summaries and (env is None or sheet_summaries[m].get("env") == env)
    ]
    # Sheet TOTAL row is authoritative for OpenPnL / RLZD / Delta / MaxProfit when filtering by month.
    # net_credit_at_risk and max_loss_exposed stay trade-level (sum of NC / MaxLoss across active trades).
    max_profit_total = sum(float(t.get("net_credit") or 0) for t in trades if t.get("is_active"))
    if selected_summaries:
        open_pnl = sum(float(s.get("open_pnl") or 0) for s in selected_summaries)
        rlzd = sum(float(s.get("rlzd") or 0) for s in selected_summaries)
        delta_total = sum(float(s.get("delta") or 0) for s in selected_summaries)
        sheet_max_profit = sum(float(s.get("max_profit") or 0) for s in selected_summaries)
        if sheet_max_profit:
            max_profit_total = sheet_max_profit

    return KpisResponse(
        filter=FilterEcho(months=months, env=env),
        pnl={
            "open": round(open_pnl, 2),
            "rlzd": round(rlzd, 2),
            "delta": round(delta_total, 2),
            "max_profit": round(max_profit_total, 2),
        },
        risk={
            "max_loss_exposed": round(max_loss_exposed, 2),
            "net_credit_at_risk": round(net_credit_at_risk, 2),
            "est_daily_theta": round(daily_theta, 2),
        },
        performance={
            "win_rate": round(win_rate, 4) if win_rate is not None else None,
            "profit_factor": round(profit_factor, 2) if profit_factor is not None else None,
            "expectancy": round(expectancy, 2) if expectancy is not None else None,
        },
        trade_intel={
            "best_trade": round(max(closed_pnls), 2) if closed_pnls else None,
            "worst_trade": round(min(closed_pnls), 2) if closed_pnls else None,
            "n_active": n_active,
            "n_closed": n_closed,
        },
    )


@app.get("/api/analytics")
def get_analytics(
    month: str | None = Query(None),
    env: str | None = Query(None),
) -> JSONResponse:
    snap = load_snapshot()
    months = parse_months(month)
    individual_pnls = snap.get("individual_trade_pnls") or {}
    sheet_summaries = sheet_summary_lookup(snap)
    sheet_daily_pnls = snap.get("sheet_daily_pnls") or {}

    def valid_month_trade(t: dict[str, Any]) -> bool:
        sheet = (t.get("sheet") or "").strip()
        if not sheet or not MONTH_SHEET_REGEX.match(sheet):
            return False
        if months and sheet not in months:
            return False
        if env and t.get("environment") != env:
            return False
        return True

    trades = [t for t in snap.get("trades", []) if valid_month_trade(t)]
    months_in_scope = months or sorted({t.get("sheet") for t in trades if t.get("sheet")}, key=lambda s: _month_sort_tuple(str(s)))

    def pnl_for(t: dict[str, Any]) -> float:
        return trade_pnl(t, individual_pnls)

    def aggregate(key_fn, source_trades: list[dict[str, Any]] | None = None) -> list[dict[str, Any]]:
        groups: dict[str, dict[str, Any]] = {}
        rows = source_trades if source_trades is not None else trades
        for t in rows:
            key = key_fn(t) or "Unknown"
            pnl = pnl_for(t)
            g = groups.setdefault(key, {"key": key, "pnl": 0.0, "n_trades": 0, "wins": 0, "losses": 0, "active": 0})
            g["pnl"] += pnl
            g["n_trades"] += 1
            g["wins"] += int(pnl > 0)
            g["losses"] += int(pnl < 0)
            g["active"] += int(bool(t.get("is_active")))
        rows = []
        for g in groups.values():
            n = g["n_trades"]
            rows.append({
                **g,
                "pnl": round(g["pnl"], 2),
                "win_rate": round(g["wins"] / n, 4) if n else None,
                "avg_pnl": round(g["pnl"] / n, 2) if n else None,
            })
        return sorted(rows, key=lambda r: abs(float(r["pnl"])), reverse=True)

    pnls = [pnl_for(t) for t in trades]
    wins = [p for p in pnls if p > 0]
    losses = [p for p in pnls if p < 0]
    total_pnl = sum(pnls)
    profit_factor = (sum(wins) / abs(sum(losses))) if losses and sum(losses) else None

    by_month = []
    for sheet in months_in_scope:
        if not sheet:
            continue
        month_trades = [t for t in trades if t.get("sheet") == sheet]
        summary = sheet_summaries.get(str(sheet), {})
        pnl = float(summary.get("open_pnl") or 0) + float(summary.get("rlzd") or 0) if summary else sum(pnl_for(t) for t in month_trades)
        by_month.append({
            "key": sheet,
            "label": _pretty_month_label(str(sheet)),
            "pnl": round(pnl, 2),
            "open_pnl": round(float(summary.get("open_pnl") or 0), 2) if summary else 0.0,
            "rlzd": round(float(summary.get("rlzd") or 0), 2) if summary else 0.0,
            "n_trades": len(month_trades),
            "active": any(t.get("is_active") for t in month_trades),
        })

    by_strategy = aggregate(lambda t: strategy_family(str(t.get("name", ""))))
    by_underlying = aggregate(lambda t: t.get("underlying") or "Unknown")
    by_dte_bucket = aggregate(trade_dte_bucket)
    by_weekday = aggregate(trade_open_weekday)
    by_day = []
    daily_groups: dict[str, dict[str, Any]] = {}
    has_total_daily_path = False
    for sheet in months_in_scope:
        for row in sheet_daily_pnls.get(str(sheet), []) or []:
            day = str(row.get("date") or "")
            if not day:
                continue
            has_total_daily_path = has_total_daily_path or row.get("pnl_type") == "total_open_plus_rlzd" or "open_pnl" in row or "rlzd" in row
            g = daily_groups.setdefault(
                day,
                {"key": day, "pnl": 0.0, "open_pnl": 0.0, "rlzd": 0.0, "daily_pnl": 0.0, "n_trades": 0, "trades": []},
            )
            g["pnl"] += float(row.get("pnl") or 0)
            g["open_pnl"] += float(row.get("open_pnl") or 0)
            g["rlzd"] += float(row.get("rlzd") or 0)
            g["daily_pnl"] += float(row.get("daily_pnl") or row.get("pnl") or 0)
            g["n_trades"] += int(row.get("n_trades") or 0)
            g["trades"].extend(row.get("trades") or [])
    if daily_groups:
        for row in sorted(daily_groups.values(), key=lambda r: str(r["key"])):
            pnl = round(float(row["pnl"]), 2)
            if has_total_daily_path:
                by_day.append({
                    **row,
                    "pnl": pnl,
                    "open_pnl": round(float(row.get("open_pnl") or 0), 2),
                    "rlzd": round(float(row.get("rlzd") or 0), 2),
                    "daily_pnl": round(float(row.get("daily_pnl") or 0), 2),
                })
            else:
                by_day.append({**row, "pnl": pnl})
    else:
        by_day_raw = aggregate(trade_pnl_event_date)
        cumulative_pnl = 0.0
        for row in sorted(by_day_raw, key=lambda r: str(r["key"])):
            cumulative_pnl += float(row["pnl"])
            by_day.append({**row, "cumulative_pnl": round(cumulative_pnl, 2)})
    closed_trades = [t for t in trades if not t.get("is_active")]
    closed_with_close_weekday = [t for t in closed_trades if trade_close_weekday(t) != "Unknown"]
    by_close_weekday = aggregate(trade_close_weekday, closed_with_close_weekday)
    days_held = [d for t in closed_trades if (d := trade_days_held(t)) is not None]

    top_winners = sorted([t for t in trades if pnl_for(t) > 0], key=pnl_for, reverse=True)[:5]
    top_losers = sorted([t for t in trades if pnl_for(t) < 0], key=pnl_for)[:5]

    insights = []
    if by_strategy:
        best_strategy = max(by_strategy, key=lambda r: float(r["pnl"]))
        worst_strategy = min(by_strategy, key=lambda r: float(r["pnl"]))
        insights.append({"label": "Best strategy family", "value": best_strategy["key"], "detail": best_strategy["pnl"]})
        insights.append({"label": "Worst strategy family", "value": worst_strategy["key"], "detail": worst_strategy["pnl"]})
    if by_dte_bucket:
        best_dte_bucket = max(by_dte_bucket, key=lambda r: float(r["pnl"]))
        insights.append({"label": "Best DTE bucket", "value": best_dte_bucket["key"], "detail": best_dte_bucket["pnl"]})
    if losses:
        insights.append({"label": "Loss concentration", "value": f"{abs(min(losses)) / abs(sum(losses)):.0%}", "detail": "largest loss / total gross losses"})

    return JSONResponse({
        "filter": {"months": months, "env": env},
        "summary": {
            "total_pnl": round(total_pnl, 2),
            "n_trades": len(trades),
            "n_active": sum(1 for t in trades if t.get("is_active")),
            "win_rate": round(len(wins) / len(pnls), 4) if pnls else None,
            "avg_win": round(sum(wins) / len(wins), 2) if wins else None,
            "avg_loss": round(sum(losses) / len(losses), 2) if losses else None,
            "profit_factor": round(profit_factor, 2) if profit_factor is not None else None,
            "avg_days_held": round(sum(days_held) / len(days_held), 2) if days_held else None,
        },
        "by_month": by_month,
        "by_strategy": by_strategy,
        "by_underlying": by_underlying,
        "by_dte_bucket": by_dte_bucket,
        "by_weekday": by_weekday,
        "by_day": by_day,
        "by_close_weekday": by_close_weekday,
        "top_winners": [_analytics_trade(t, pnl_for(t)) for t in top_winners],
        "top_losers": [_analytics_trade(t, pnl_for(t)) for t in top_losers],
        "insights": insights,
    })


# ─── Backtests ────────────────────────────────────────────────────────────────

BACKTESTS_ROOT = REPO_ROOT / "reports"

BACKTESTS_REGISTRY: list[dict[str, Any]] = [
    {
        "id": "ss42-spx",
        "name": "Short Strangle 42 DTE",
        "underlying": "SPX",
        "strategy": "Short Strangle",
        "horizon": "42 DTE",
        "trades_csv": "ss42_backtest/SS42_SPX_2025-05-02_2026-04-02.csv",
        "daily_csv": "ss42_backtest/SS42_SPX_daily_2025-05-02_2026-04-02.csv",
        "kind": "ss42",
        "multiplier": 100,
    },
    {
        "id": "ss42-rut",
        "name": "Short Strangle 42 DTE",
        "underlying": "RUT",
        "strategy": "Short Strangle",
        "horizon": "42 DTE",
        "trades_csv": "ss42_backtest/SS42_RUT_2025-05-02_2026-04-02.csv",
        "daily_csv": "ss42_backtest/SS42_RUT_daily_2025-05-02_2026-04-02.csv",
        "kind": "ss42",
        "multiplier": 100,
    },
    {
        "id": "ic7-ndx",
        "name": "Iron Condor 7 DTE",
        "underlying": "NDX",
        "strategy": "Iron Condor",
        "horizon": "7 DTE",
        "trades_csv": "ic7_backtest/IC7_7DTE_NDX_2025-05-02_2026-03-27.csv",
        "daily_csv": "ic7_backtest/IC7_7DTE_NDX_daily_2025-05-02_2026-03-27.csv",
        "kind": "ic7",
        "multiplier": 100,
    },
]

_backtest_csv_cache: dict[str, dict[str, Any]] = {}


def _backtest_meta(bt_id: str) -> dict[str, Any]:
    for bt in BACKTESTS_REGISTRY:
        if bt["id"] == bt_id:
            return bt
    raise HTTPException(404, f"Backtest '{bt_id}' not found")


def _sanitize_records(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Replace NaN/Inf floats with None so the result is JSON-serializable."""
    import math

    out: list[dict[str, Any]] = []
    for row in records:
        clean: dict[str, Any] = {}
        for k, v in row.items():
            if isinstance(v, float) and (math.isnan(v) or math.isinf(v)):
                clean[k] = None
            else:
                clean[k] = v
        out.append(clean)
    return out


def _parse_csv_value(value: str | None) -> Any:
    if value is None:
        return None
    value = value.strip()
    if value == "":
        return None
    lowered = value.lower()
    if lowered == "true":
        return True
    if lowered == "false":
        return False
    try:
        if "." not in value and "e" not in lowered:
            return int(value)
        return float(value)
    except ValueError:
        return value


def _read_backtest_csv(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    mtime = path.stat().st_mtime
    cached = _backtest_csv_cache.get(str(path))
    if cached and cached.get("mtime") == mtime:
        return cached["rows"]
    with path.open(newline="", encoding="utf-8-sig") as f:
        rows = [
            {k: _parse_csv_value(v) for k, v in row.items()}
            for row in csv.DictReader(f)
        ]
    rows = _sanitize_records(rows)
    _backtest_csv_cache[str(path)] = {"mtime": mtime, "rows": rows}
    return rows


def _read_backtest_trades(meta: dict[str, Any]) -> list[dict[str, Any]]:
    return _read_backtest_csv(BACKTESTS_ROOT / meta["trades_csv"])


def _read_backtest_daily(meta: dict[str, Any]) -> list[dict[str, Any]]:
    return _read_backtest_csv(BACKTESTS_ROOT / meta["daily_csv"])


SS42_RULES = [
    "Hold to Expiration",
    "25% Profit Target",
    "50% Profit Target",
    "75% Profit Target",
    "50% Profit or 24 DIT",
    "24 DIT",
]
IC7_RULES = [
    "Hold to Expiration",
    "25% Profit Target",
    "50% Profit Target",
    "75% Profit Target",
    "4 DTE",
    "Stop: 1× Max Profit",
]


def _scan_close_rule(
    trade: dict[str, Any],
    daily: list[dict[str, Any]],
    rule: str,
    multiplier: int,
) -> tuple[float, str | None, int | None]:
    """
    Walks the daily MTM rows for a single trade and returns
    (effective_pnl_usd, close_date_iso, dit_at_close).
    Falls back to the trade's expiration pnl if no trigger fires.
    """
    fallback = float(trade.get("pnl_usd") or 0)
    if rule == "Hold to Expiration":
        return fallback, str(trade.get("exp_date")) if trade.get("exp_date") else None, None

    trade_date = str(trade.get("trade_date"))
    rows = [r for r in daily if str(r.get("trade_date")) == trade_date]
    if not rows:
        return fallback, str(trade.get("exp_date")) if trade.get("exp_date") else None, None

    rows = sorted(rows, key=lambda r: int(r.get("dte_remaining") or 0), reverse=True)
    entry_dte = int(rows[0].get("dte_remaining") or 0)
    scan = [r for r in rows if int(r.get("dte_remaining") or 0) < entry_dte]

    max_p = float(trade.get("total_credit") or 0) * multiplier
    tp_pct = None
    sl_pct = None
    dit_target = None
    dte_target = None

    if rule == "25% Profit Target":
        tp_pct = 0.25
    elif rule == "50% Profit Target":
        tp_pct = 0.50
    elif rule == "75% Profit Target":
        tp_pct = 0.75
    elif rule == "24 DIT":
        dit_target = 24
    elif rule == "50% Profit or 24 DIT":
        tp_pct = 0.50
        dit_target = 24
    elif rule == "4 DTE":
        dte_target = 4
    elif rule == "Stop: 1× Max Profit":
        sl_pct = -1.0

    tp_thr = tp_pct * max_p if tp_pct is not None and max_p else None
    sl_thr = sl_pct * max_p if sl_pct is not None and max_p else None

    for r in scan:
        pnl_val = r.get("pnl_usd")
        if pnl_val is None:
            continue
        pnl = float(pnl_val)
        dte = int(r.get("dte_remaining") or 0)
        dit = entry_dte - dte
        triggered = False
        if tp_thr is not None and pnl >= tp_thr:
            triggered = True
        elif sl_thr is not None and pnl <= sl_thr:
            triggered = True
        elif dit_target is not None and dit >= dit_target:
            triggered = True
        elif dte_target is not None and dte <= dte_target:
            triggered = True
        if triggered:
            return pnl, str(r.get("calendar_date")), dit

    return fallback, str(trade.get("exp_date")) if trade.get("exp_date") else None, None


def _apply_rule(
    trades: list[dict[str, Any]],
    daily: list[dict[str, Any]],
    rule: str,
    multiplier: int,
) -> list[dict[str, Any]]:
    """Returns shallow copies of trades with effective_pnl_usd / effective_close_date set."""
    out: list[dict[str, Any]] = []
    for t in trades:
        eff_pnl, close_date, dit = _scan_close_rule(t, daily, rule, multiplier)
        nt = dict(t)
        nt["effective_pnl_usd"] = eff_pnl
        nt["effective_close_date"] = close_date
        nt["effective_dit_at_close"] = dit
        # Keep raw exp pnl for reference
        nt["pnl_usd_at_exp"] = float(t.get("pnl_usd") or 0)
        # The rule-based PnL becomes the canonical pnl_usd for KPI computation downstream
        nt["pnl_usd"] = eff_pnl
        out.append(nt)
    return out


def _backtest_kpis(trades: list[dict[str, Any]]) -> dict[str, Any]:
    closed = [t for t in trades if (t.get("exit_method") or "").lower() != "fallback_entry"]
    pnls = [float(t.get("pnl_usd") or 0) for t in closed]
    wins = [p for p in pnls if p > 0]
    losses = [p for p in pnls if p < 0]
    total = sum(pnls)
    n = len(pnls)
    win_rate = len(wins) / n if n else None
    profit_factor = (sum(wins) / abs(sum(losses))) if losses and sum(losses) else None
    avg_win = (sum(wins) / len(wins)) if wins else None
    avg_loss = (sum(losses) / len(losses)) if losses else None
    payoff = (abs(avg_win) / abs(avg_loss)) if avg_win and avg_loss else None
    expectancy = (sum(pnls) / n) if n else None
    in_range_count = sum(1 for t in closed if bool(t.get("in_range")))
    in_range_rate = in_range_count / n if n else None
    # Equity & drawdown
    equity = []
    cum = 0.0
    peak = 0.0
    max_dd = 0.0
    for t in closed:
        cum += float(t.get("pnl_usd") or 0)
        peak = max(peak, cum)
        dd = cum - peak
        max_dd = min(max_dd, dd)
        equity.append({
            "trade_date": t.get("trade_date"),
            "exp_date": t.get("exp_date"),
            "pnl_usd": float(t.get("pnl_usd") or 0),
            "cumulative_pnl": round(cum, 2),
            "drawdown": round(dd, 2),
        })
    # Sharpe approximated with per-trade pnl as returns (no risk-free; informative only)
    sharpe = None
    if len(pnls) > 1:
        import statistics
        std = statistics.pstdev(pnls)
        if std > 0:
            sharpe = round((expectancy or 0) / std * (52 ** 0.5), 3)
    # Max consecutive losses
    max_streak = streak = 0
    for p in pnls:
        if p < 0:
            streak += 1
            max_streak = max(max_streak, streak)
        else:
            streak = 0
    return {
        "n_trades": n,
        "n_open": len(trades) - n,
        "wins": len(wins),
        "losses": len(losses),
        "total_pnl": round(total, 2),
        "best_trade": round(max(pnls), 2) if pnls else None,
        "worst_trade": round(min(pnls), 2) if pnls else None,
        "win_rate": round(win_rate, 4) if win_rate is not None else None,
        "profit_factor": round(profit_factor, 3) if profit_factor is not None else None,
        "avg_win": round(avg_win, 2) if avg_win is not None else None,
        "avg_loss": round(avg_loss, 2) if avg_loss is not None else None,
        "payoff": round(payoff, 2) if payoff is not None else None,
        "expectancy": round(expectancy, 2) if expectancy is not None else None,
        "in_range_rate": round(in_range_rate, 4) if in_range_rate is not None else None,
        "max_drawdown": round(max_dd, 2),
        "sharpe": sharpe,
        "max_consecutive_losses": max_streak,
        "equity": equity,
    }


def _period_label(trades: list[dict[str, Any]]) -> str | None:
    if not trades:
        return None
    starts = [t.get("trade_date") for t in trades if t.get("trade_date")]
    ends = [t.get("exp_date") for t in trades if t.get("exp_date")]
    if not starts or not ends:
        return None
    return f"{min(starts)} → {max(ends)}"


@app.get("/api/backtests")
def list_backtests() -> JSONResponse:
    summaries = []
    for bt in BACKTESTS_REGISTRY:
        trades = _read_backtest_trades(bt)
        kpis = _backtest_kpis(trades)
        summaries.append({
            "id": bt["id"],
            "name": bt["name"],
            "underlying": bt["underlying"],
            "strategy": bt["strategy"],
            "horizon": bt["horizon"],
            "period": _period_label(trades),
            "kpis": {
                "n_trades": kpis["n_trades"],
                "n_open": kpis["n_open"],
                "total_pnl": kpis["total_pnl"],
                "win_rate": kpis["win_rate"],
                "profit_factor": kpis["profit_factor"],
                "max_drawdown": kpis["max_drawdown"],
                "sharpe": kpis["sharpe"],
            },
        })
    return JSONResponse({"backtests": summaries})


@app.get("/api/backtests/{bt_id}")
def get_backtest(
    bt_id: str,
    rule: str = Query("Hold to Expiration", description="Close management rule"),
) -> JSONResponse:
    meta = _backtest_meta(bt_id)
    raw_trades = _read_backtest_trades(meta)
    daily = _read_backtest_daily(meta)

    available_rules = SS42_RULES if meta["kind"] == "ss42" else IC7_RULES
    rule_to_use = rule if rule in available_rules else "Hold to Expiration"

    trades_with_rule = _apply_rule(raw_trades, daily, rule_to_use, meta["multiplier"])
    kpis = _backtest_kpis(trades_with_rule)

    display_cols_ss42 = [
        "trade_date", "exp_date", "underlying", "dte_entry", "spot_entry", "iv_atm_pct",
        "vix_entry", "short_put", "short_call", "delta_put", "delta_call", "total_credit",
        "spot_exit", "pnl_usd", "pnl_usd_at_exp", "effective_close_date",
        "effective_dit_at_close", "in_range", "result", "exit_method",
    ]
    display_cols_ic7 = [
        "trade_date", "exp_date", "spot_entry", "atm_strike", "iv_atm_pct", "expected_move",
        "em_pct", "short_put", "long_put", "short_call", "long_call", "total_credit",
        "spot_exit", "pnl_usd", "pnl_usd_at_exp", "effective_close_date",
        "effective_dit_at_close", "max_risk_usd", "in_range", "result", "exit_method",
    ]
    cols = display_cols_ss42 if meta["kind"] == "ss42" else display_cols_ic7
    trades_view = [{c: t.get(c) for c in cols} for t in trades_with_rule]
    return JSONResponse({
        "meta": {
            "id": meta["id"],
            "name": meta["name"],
            "underlying": meta["underlying"],
            "strategy": meta["strategy"],
            "horizon": meta["horizon"],
            "kind": meta["kind"],
            "period": _period_label(raw_trades),
            "multiplier": meta["multiplier"],
            "rule": rule_to_use,
            "available_rules": available_rules,
        },
        "kpis": kpis,
        "trades": trades_view,
        "daily": daily,
    })


@app.post("/api/chat")
async def chat(req: ChatRequest, request: Request) -> StreamingResponse:
    snap = load_snapshot()
    months = req.filter.months
    env = req.filter.env
    trades = [t for t in snap.get("trades", []) if trade_in_filter(t, months, env)]

    system_prompt = _build_system_prompt(trades, snap, months, env)
    messages = [{"role": m.role, "content": m.content} for m in req.messages if m.role != "system"]

    if req.provider == "anthropic":
        return StreamingResponse(_stream_anthropic(system_prompt, messages), media_type="text/event-stream")
    return StreamingResponse(_stream_openai(system_prompt, messages), media_type="text/event-stream")


# ─── Internals ────────────────────────────────────────────────────────────────


def _month_sort_tuple(sheet: str) -> tuple[int, int, str]:
    code = sheet.split()[-1]
    mon = code[:3]
    year = int(code[3:]) if len(code) == 5 and code[3:].isdigit() else -1
    return (year, MONTH_NUM.get(mon, -1), sheet)


def _month_filter_sort_tuple(month: MonthInfo) -> tuple[int, int, int, str]:
    group = 1 if month.sheet.upper().startswith("JS") else 0
    year, month_num, sheet = _month_sort_tuple(month.sheet)
    return (group, -year, -month_num, sheet)


def _analytics_trade(trade: dict[str, Any], pnl: float) -> dict[str, Any]:
    return {
        "name": trade.get("name"),
        "sheet": trade.get("sheet"),
        "underlying": trade.get("underlying"),
        "strategy": strategy_family(str(trade.get("name", ""))),
        "dte_bucket": trade_dte_bucket(trade),
        "open_weekday": trade_open_weekday(trade),
        "close_weekday": trade_close_weekday(trade),
        "days_held": trade_days_held(trade),
        "pnl": round(pnl, 2),
        "is_active": bool(trade.get("is_active")),
    }


def _pretty_month_label(sheet: str) -> str:
    # APR26 → "Apr 2026"; "JS APR26" → "JS Apr 2026"; "FOR Trades" → "FOR Trades"
    months_map = {
        "JAN": "Jan", "FEB": "Feb", "MAR": "Mar", "APR": "Apr", "MAY": "May", "JUN": "Jun",
        "JUL": "Jul", "AUG": "Aug", "SEP": "Sep", "OCT": "Oct", "NOV": "Nov", "DEC": "Dec",
    }
    parts = sheet.split()
    out: list[str] = []
    for p in parts:
        if len(p) == 5 and p[:3] in months_map and p[3:].isdigit():
            out.append(f"{months_map[p[:3]]} 20{p[3:]}")
        else:
            out.append(p)
    return " ".join(out)


def _weekday_sort_key(day: str) -> int:
    order = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun", "Unknown"]
    return order.index(day) if day in order else len(order)


def _weekday_label(day: str) -> str:
    labels = {
        "Mon": "Mon/Monday",
        "Tue": "Tue/Tuesday",
        "Wed": "Wed/Wednesday",
        "Thu": "Thu/Thursday",
        "Fri": "Fri/Friday",
        "Sat": "Sat/Saturday",
        "Sun": "Sun/Sunday",
    }
    return labels.get(day, day)


def _fmt_money(value: float) -> str:
    return f"${value:,.0f}"


def _build_scope_metrics(trades: list[dict[str, Any]], individual: dict[str, float]) -> str:
    open_weekday_pnl: dict[str, float] = {}
    close_weekday_pnl: dict[str, float] = {}
    holding_days: list[int] = []

    for t in trades:
        pnl = trade_pnl(t, individual)
        open_day = trade_open_weekday(t)
        open_weekday_pnl[open_day] = open_weekday_pnl.get(open_day, 0.0) + pnl

        close_day = trade_close_weekday(t)
        if close_day != "Unknown":
            close_weekday_pnl[close_day] = close_weekday_pnl.get(close_day, 0.0) + pnl

        days = trade_days_held(t)
        if days is not None:
            holding_days.append(days)

    def fmt_weekday_totals(rows: dict[str, float]) -> str:
        if not rows:
            return "unavailable"
        return ", ".join(
            f"{_weekday_label(day)}={_fmt_money(rows[day])}"
            for day in sorted(rows, key=_weekday_sort_key)
        )

    if holding_days:
        avg_days = sum(holding_days) / len(holding_days)
        holding_desc = f"n={len(holding_days)}, avg={avg_days:.2f} calendar days"
        holding_answer = f"avg={avg_days:.2f} calendar days over n={len(holding_days)} closed trades"
    else:
        holding_desc = "unavailable"
        holding_answer = "unavailable"

    best_open = max(open_weekday_pnl.items(), key=lambda item: item[1]) if open_weekday_pnl else None
    best_close = max(close_weekday_pnl.items(), key=lambda item: item[1]) if close_weekday_pnl else None
    best_open_desc = f"{_weekday_label(best_open[0])}={_fmt_money(best_open[1])}" if best_open else "unavailable"
    best_close_desc = f"{_weekday_label(best_close[0])}={_fmt_money(best_close[1])}" if best_close else "unavailable"

    return (
        "Authoritative computed metrics in scope:\n"
        "- Weekday key: Mon=Monday, Tue=Tuesday, Wed=Wednesday, Thu=Thursday, Fri=Friday.\n"
        f"- Best opening weekday by PnL: {best_open_desc}\n"
        f"- Best inferred close weekday by PnL: {best_close_desc}\n"
        f"- Opening weekday PnL: {fmt_weekday_totals(open_weekday_pnl)}\n"
        f"- Inferred close weekday PnL: {fmt_weekday_totals(close_weekday_pnl)}\n"
        f"- Closed-trade holding period from inferred close dates: {holding_desc}\n"
        f"- If asked average holding time, copy this exact metric: {holding_answer}\n"
    )


def _build_system_prompt(trades: list[dict[str, Any]], snap: dict[str, Any], months: list[str], env: str | None) -> str:
    filter_desc = f"months={months or 'ALL'}, env={env or 'ALL'}"
    individual = snap.get("individual_trade_pnls") or {}
    scope_metrics = _build_scope_metrics(trades, individual)
    trade_lines: list[str] = []
    for t in trades:
        name = t.get("name", "?")
        pnl = trade_pnl(t, individual)
        trade_lines.append(
            f"- {name} ({t.get('underlying','?')}, sheet={t.get('sheet') or '?'}, "
            f"strategy={strategy_family(name)}, dte_bucket={trade_dte_bucket(t)}, "
            f"open_weekday={trade_open_weekday(t)}, "
            f"open_date={t.get('visual_open_date') or t.get('open_date') or '?'}, "
            f"exp_date={t.get('visual_exp_date') or t.get('exp_date') or '?'}, "
            f"dte_open={t.get('visual_dte_open') or t.get('dte_open') or '?'}, "
            f"last_pnl_date={t.get('visual_last_pnl_date') or '?'}, "
            f"last_pnl_weekday={t.get('visual_last_pnl_weekday') or '?'}, "
            f"inferred_close_date={t.get('inferred_close_date') or '?'}, "
            f"inferred_close_weekday={t.get('inferred_close_weekday') or '?'}, "
            f"days_held={t.get('days_held') if t.get('days_held') is not None else '?'}, "
            f"days_open_as_of_last_pnl={t.get('days_open_as_of_last_pnl') if t.get('days_open_as_of_last_pnl') is not None else '?'}): "
            f"PnL=${pnl:.0f}, status={'ACTIVE' if t.get('is_active') else 'CLOSED'}, "
            f"Δ={trade_delta(t):.1f}, DTE={t.get('dte_remaining','—')}, "
            f"NC=${t.get('net_credit','—')}, MaxLoss=${t.get('max_loss','—')}"
        )
    trade_block = "\n".join(trade_lines) if trade_lines else "(no trades match the current filter)"

    return (
        "You are the ST | Dashboard AI — an analytical assistant embedded in Cristiano's "
        "proprietary trading desk dashboard. Your primary source of truth is the trade "
        "context shown below. You analyze it to identify leaks, correlations, strengths, "
        "weaknesses, and structural patterns. You may also discuss options strategy design, "
        "risk management, volatility selling concepts, technical-analysis frameworks, "
        "backtest methodology, and general market structure when the user asks broader "
        "research questions. You have access to live web search; use it when the user asks "
        "for current facts such as news, VIX level, market prices, macro calendar, or recent "
        "events.\n\n"
        f"Active filter: {filter_desc}\n"
        f"Snapshot generated at: {snap.get('generated_at','?')}\n\n"
        f"{scope_metrics}\n"
        f"Trades in scope:\n{trade_block}\n\n"
        "Hard rules:\n"
        "- NEVER recommend specific trade execution (entry/exit). Cristiano executes; you analyze.\n"
        "- Answer like a senior quant analyst in a ChatGPT-style conversation: clear, structured, sufficiently detailed, and practical. Do not be terse unless the user asks for a short answer.\n"
        "- When discussing PnL, always cite the specific trade names from above.\n"
        "- If asked about live/current external data (news, VIX level, market prices, IV Rank, GEX, macro calendar, or broker data), use web search when available and cite sources. If web search fails or cannot verify the fact, say that clearly. Do not invent current facts.\n"
        "- If asked about strategies or research not directly present in the trade list, answer from general options/quant knowledge and clearly label it as general research, not a conclusion from the current book.\n"
        "- For current market questions, separate verified web facts from inferences about the desk's current trades.\n"
        "- Answer in the user's language.\n"
        "- Use clean Markdown: short headings, bullets, and compact tables for comparisons. Include an executive summary first for long answers.\n"
        "- Keep calculations auditable: show totals and the trade names behind them, but avoid long arithmetic walls.\n"
        "- Treat 'Authoritative computed metrics in scope' as the source of truth for weekday PnL and holding-period questions.\n"
        "- If your manual reasoning conflicts with the authoritative computed metrics, use the authoritative computed metrics.\n"
        "- For average holding period questions, copy the exact 'average holding time' metric from the authoritative block; do not recompute it from individual trade rows.\n"
        "- For counts, count the matching trade rows exactly before answering.\n"
        "- For holding period, use days_held only for CLOSED trades. Exclude rows where days_held is unknown and cite the sample size.\n"
        "- Do not use remaining DTE as holding period. For ACTIVE trades, days_open_as_of_last_pnl is current age, not final holding period.\n"
        "- You may analyze planned opening horizon using dte_open, but label it as opening DTE, not holding time.\n"
    )


async def _stream_anthropic(system: str, messages: list[dict[str, str]]) -> Iterable[bytes]:
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        yield _sse({"error": "ANTHROPIC_API_KEY not set", "done": True})
        return
    try:
        from anthropic import AsyncAnthropic
    except ImportError:
        yield _sse({"error": "anthropic SDK not installed", "done": True})
        return

    client = AsyncAnthropic(api_key=api_key)
    try:
        async with client.messages.stream(
            model="claude-sonnet-4-6",
            max_tokens=4096,
            system=system,
            messages=messages,
            tools=[{"type": "web_search_20250305", "name": "web_search", "max_uses": 5}],
        ) as stream:
            async for text in stream.text_stream:
                yield _sse({"delta": text, "done": False})
        yield _sse({"done": True})
    except Exception as exc:
        yield _sse({"error": f"Anthropic API error: {exc}", "done": True})


async def _stream_openai(system: str, messages: list[dict[str, str]]) -> Iterable[bytes]:
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        yield _sse({"error": "OPENAI_API_KEY not set", "done": True})
        return
    try:
        from openai import AsyncOpenAI
    except ImportError:
        yield _sse({"error": "openai SDK not installed", "done": True})
        return

    client = AsyncOpenAI(api_key=api_key)
    response_input = [
        {"role": m["role"], "content": m["content"]}
        for m in messages
        if m["role"] in ("user", "assistant")
    ]
    try:
        stream = await client.responses.create(
            model="gpt-5.5",
            instructions=system,
            input=response_input,
            tools=[{"type": "web_search"}],
            tool_choice="auto",
            reasoning={"effort": "medium"},
            text={"verbosity": "medium"},
            max_output_tokens=4096,
            stream=True,
        )
        async for event in stream:
            if getattr(event, "type", None) == "response.error":
                error = getattr(event, "error", None)
                yield _sse({"error": f"OpenAI API error: {error}", "done": True})
                return
            if getattr(event, "type", None) != "response.output_text.delta":
                continue
            delta = getattr(event, "delta", None)
            if delta:
                yield _sse({"delta": delta, "done": False})
        yield _sse({"done": True})
    except Exception as exc:
        yield _sse({"error": f"OpenAI API error: {exc}", "done": True})


def _sse(payload: dict[str, Any]) -> bytes:
    return f"data: {json.dumps(payload, ensure_ascii=False)}\n\n".encode("utf-8")
